name: Portfolio Deployment
on: 
  push:
    branches:
      -main
  workflow_dispatch:
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the purpose of run
        run: echo "Purpose Deploying portfolio or running tests"    
