name: Portfolio Deployment
on: 
  push:
    branches:
      -main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: page_deploy
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Print the purpose of run
        run: echo "Purpose Deploying portfolio or running tests"
      - name: Checking out code
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-actions@releases/v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: main
          FOLDER: For Testing

